# Generated by Django 5.2.9 on 2025-12-09 11:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('grade_band', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('researcher', 'Researcher')], default='student', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.site')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ItemBankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_html', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq_single', 'Multiple choice (single)'), ('mcq_multi', 'Multiple choice (multi)'), ('true_false', 'True / False'), ('short_answer', 'Short answer'), ('long_answer', 'Long answer'), ('matching', 'Matching'), ('ordering', 'Ordering'), ('cloze', 'Cloze'), ('file_upload', 'File upload')], max_length=20)),
                ('default_points', models.FloatField(default=1.0)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('grade_band', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_bank_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemBankChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=5)),
                ('text_html', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.itembankquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('introduction_html', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_modes', models.JSONField(default=list)),
                ('default_mode', models.CharField(choices=[('continuous', 'Continuous'), ('cards', 'Cards'), ('movie', 'Movie')], default='continuous', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_start', models.DateTimeField(blank=True, null=True)),
                ('reading_end', models.DateTimeField(blank=True, null=True)),
                ('quiz_start', models.DateTimeField(blank=True, null=True)),
                ('quiz_end', models.DateTimeField(blank=True, null=True)),
                ('comprehension_score', models.FloatField(blank=True, null=True)),
                ('self_efficacy_rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='core.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('file_path', models.CharField(max_length=500)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('instructions_html', models.TextField(blank=True)),
                ('total_points', models.FloatField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.quiz'),
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('points', models.FloatField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.itembankquestion')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='core.quiz')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('raw_score', models.FloatField(blank=True, null=True)),
                ('max_score', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizSubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=20)),
                ('selected_choice_ids', models.JSONField(blank=True, default=list)),
                ('short_answer_text', models.TextField(blank=True)),
                ('long_answer_text', models.TextField(blank=True)),
                ('file_upload_path', models.CharField(blank=True, max_length=500)),
                ('file_metadata', models.JSONField(blank=True, default=dict)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('partial_credit_ratio', models.FloatField(blank=True, null=True)),
                ('time_spent_seconds', models.FloatField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.itembankquestion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.quizsubmission')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='rosters',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='core.roster'),
        ),
        migrations.AddField(
            model_name='roster',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.site'),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text_html', models.TextField()),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('ai_generated', 'AI Generated'), ('external', 'External')], default='manual', max_length=20)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('reading_level_label', models.CharField(blank=True, max_length=100)),
                ('reading_level_metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('start', 'Start'), ('scroll', 'Scroll'), ('pause', 'Pause'), ('resume', 'Resume'), ('finish', 'Finish'), ('mode_change', 'Mode change'), ('segment_view', 'Segment view')], max_length=20)),
                ('event_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_events', to='core.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_events', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.story')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.story'),
        ),
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('language_code', models.CharField(help_text='L2 language code, e.g. en', max_length=10)),
                ('native_language_code', models.CharField(help_text='L1 language code, e.g. vi', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='glossary', to='core.story')),
            ],
        ),
        migrations.CreateModel(
            name='StorySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('text_html', models.TextField()),
                ('start_char', models.IntegerField(blank=True, null=True)),
                ('end_char', models.IntegerField(blank=True, null=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='core.story')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('story', 'index')},
            },
        ),
        migrations.CreateModel(
            name='SegmentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('background_image', 'Background image'), ('inline_image', 'Inline image'), ('audio_narration', 'Audio'), ('video_clip', 'Video')], max_length=30)),
                ('start_offset_ms', models.IntegerField(default=0)),
                ('end_offset_ms', models.IntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_links', to='core.mediaasset')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_media', to='core.storysegment')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_text', models.CharField(max_length=255)),
                ('lemma', models.CharField(blank=True, max_length=255)),
                ('part_of_speech', models.CharField(blank=True, max_length=50)),
                ('definition_html', models.TextField(help_text='L2 definition')),
                ('translation', models.CharField(blank=True, max_length=255)),
                ('translation_lang_code', models.CharField(blank=True, max_length=10)),
                ('ipa', models.CharField(blank=True, max_length=255)),
                ('difficulty_rating', models.FloatField(blank=True, null=True)),
                ('is_ai_suggested', models.BooleanField(default=False)),
                ('is_selected_for_glossary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('glossary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='core.glossary')),
            ],
        ),
        migrations.CreateModel(
            name='TermOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_char', models.IntegerField()),
                ('end_char', models.IntegerField()),
                ('token_index', models.IntegerField(blank=True, null=True)),
                ('sentence_index', models.IntegerField(blank=True, null=True)),
                ('anchor_text', models.CharField(max_length=255)),
                ('anchor_version', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='term_occurrences', to='core.storysegment')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_occurrences', to='core.story')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='core.term')),
            ],
        ),
        migrations.CreateModel(
            name='GlossClickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_info', models.JSONField(blank=True, default=dict)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gloss_click_logs', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gloss_click_logs', to='core.lesson')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.story')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.storysegment')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.term')),
                ('term_occurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.termoccurrence')),
            ],
        ),
        migrations.CreateModel(
            name='RosterMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.roster')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('roster', 'student')},
            },
        ),
    ]
