# Generated by Django 5.2.9 on 2025-12-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lesson_site_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='introduction_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
