# Generated by Django 5.2.9 on 2025-12-15 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_unit_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_memberships', to='core.lesson')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_lessons', to='core.unit')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('unit', 'lesson')},
            },
        ),
        migrations.DeleteModel(
            name='UnitStory',
        ),
    ]
