# Generated by Django 5.2.9 on 2025-12-15 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_course_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.site'),
        ),
    ]
