# Generated by Django 5.2.9 on 2025-12-15 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_roster_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to=settings.AUTH_USER_MODEL),
        ),
    ]
