# Generated by Django 5.2.9 on 2025-12-15 11:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_roster_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('openlibrary', 'Open Library'), ('gutenberg', 'Project Gutenberg')], max_length=20)),
                ('external_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, max_length=500)),
                ('cover_url', models.URLField(blank=True, max_length=1000)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('instructor', 'source', 'external_id')},
            },
        ),
    ]
