# Generated by Django 5.2.9 on 2025-12-15 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_external_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='core.story'),
        ),
        migrations.AlterField(
            model_name='externalbookmark',
            name='source',
            field=models.CharField(choices=[('openlibrary', 'Open Library'), ('gutenberg', 'Project Gutenberg'), ('opentextbook', 'Open Textbook Library')], max_length=20),
        ),
    ]
