# Generated by Django 5.2.9 on 2025-12-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_story_to_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Time limit in minutes. Leave blank for no time limit.', null=True),
        ),
    ]
