# Generated by Django 5.2.9 on 2025-12-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_quiz_time_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instructor',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='externalbookmark',
            old_name='instructor',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='instructor',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='roster',
            old_name='instructor',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='instructor',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='instructor',
            new_name='teacher',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('researcher', 'Researcher')], default='student', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='externalbookmark',
            unique_together={('teacher', 'source', 'external_id')},
        ),
    ]
