# Generated by Django 5.2.9 on 2025-12-16 03:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_instructor_to_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardsArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('content_type', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('json', 'JSON'), ('docx', 'DOCX'), ('zip', 'ZIP'), ('other', 'Other')], max_length=20)),
                ('sha256_hash', models.CharField(max_length=64)),
                ('file_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='StandardsAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'International Baccalaureate'", max_length=255)),
                ('code', models.CharField(help_text="Stable key, e.g., 'IB', 'CAMBRIDGE'", max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Standards authorities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ObjectiveNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('strand', 'Strand'), ('substrand', 'Substrand'), ('objective', 'Objective'), ('note', 'Note')], max_length=20)),
                ('code', models.CharField(blank=True, help_text="Native authority code, e.g., '(6)(1)(A)', 'CCSS.MATH.CONTENT.6.RP.A.1'", max_length=100)),
                ('text', models.TextField(help_text='Objective wording (may be short if reference-only)')),
                ('internal_code', models.CharField(blank=True, help_text="Internal numbering, e.g., '1', '1.1', '1.1.1'", max_length=50)),
                ('internal_path', models.CharField(blank=True, help_text="Full path, e.g., '1/1.1/1.1.1'", max_length=255)),
                ('internal_sort_key', models.CharField(blank=True, help_text='Stable ordering key', max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.objectivenode')),
            ],
            options={
                'ordering': ['document', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ObjectiveCodeMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_code', models.CharField(blank=True, max_length=100)),
                ('internal_code', models.CharField(max_length=50)),
                ('mapping_method', models.CharField(choices=[('algorithmic', 'Algorithmic'), ('manual_curated', 'Manual Curated'), ('hybrid', 'Hybrid')], max_length=20)),
                ('mapped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('mapped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_mappings', to=settings.AUTH_USER_MODEL)),
                ('objective_node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code_map', to='core.objectivenode')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorityProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Middle Years Programme'", max_length=255)),
                ('code', models.CharField(help_text="Stable key, e.g., 'IB_MYP', 'STATE_TX'", max_length=50)),
                ('description', models.TextField(blank=True)),
                ('provider_key', models.CharField(blank=True, help_text='Maps to provider/parser implementation', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='core.standardsauthority')),
            ],
            options={
                'ordering': ['authority', 'name'],
                'unique_together': {('authority', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StandardsDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text="e.g., 'Mathematics', 'Technology Applications'", max_length=100)),
                ('grade_level', models.CharField(help_text="e.g., 'Grade 6', 'Grades 6-8', 'HL'", max_length=50)),
                ('version_label', models.CharField(help_text="e.g., 'Adopted 2022', 'Syllabus 2025-2027'", max_length=100)),
                ('source_publisher_name', models.CharField(help_text="e.g., 'Texas Education Agency'", max_length=255)),
                ('source_publisher_type', models.CharField(blank=True, choices=[('government', 'Government'), ('nonprofit', 'Non-Profit'), ('publisher', 'Publisher'), ('testing_org', 'Testing Organization'), ('other', 'Other')], max_length=20)),
                ('source_title', models.CharField(help_text='Human-readable doc title', max_length=500)),
                ('source_url', models.URLField(help_text='Primary official URL', max_length=1000)),
                ('source_url_canonical', models.URLField(blank=True, help_text='Clean landing page URL', max_length=1000)),
                ('source_accessed_at', models.DateTimeField(blank=True, help_text='When source was fetched/verified', null=True)),
                ('source_content_type', models.CharField(blank=True, choices=[('html', 'HTML'), ('pdf', 'PDF'), ('json', 'JSON'), ('docx', 'DOCX'), ('api', 'API')], max_length=20)),
                ('source_version_label', models.CharField(blank=True, max_length=100)),
                ('source_effective_from', models.DateField(blank=True, null=True)),
                ('source_effective_until', models.DateField(blank=True, null=True)),
                ('source_license_notes', models.TextField(blank=True, help_text='Redistribution restrictions')),
                ('acquisition_method', models.CharField(choices=[('official_api', 'Official API'), ('official_web_page', 'Official Web Page'), ('official_pdf', 'Official PDF'), ('official_download_bundle', 'Official Download Bundle'), ('publisher_portal_reference_only', 'Publisher Portal (Reference Only)'), ('third_party_mirror_reference', 'Third Party Mirror (Reference)'), ('teacher_provided_upload', 'Teacher Provided Upload'), ('manual_curated', 'Manual Curated'), ('hybrid', 'Hybrid')], help_text='How objectives were obtained', max_length=50)),
                ('acquisition_notes', models.TextField(blank=True, help_text='Brief explanation of acquisition process')),
                ('evidence_sha256_raw', models.CharField(blank=True, max_length=64)),
                ('evidence_sha256_canonical', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('is_reference_only', models.BooleanField(default=False, help_text='True if only codes/structure stored due to licensing')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authority_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards_documents', to='core.authorityprogram')),
                ('evidence_artifact', models.ForeignKey(blank=True, help_text='Raw downloaded file snapshot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.standardsartifact')),
            ],
            options={
                'ordering': ['authority_program', 'subject', 'grade_level', '-version_label'],
            },
        ),
        migrations.AddField(
            model_name='objectivenode',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_nodes', to='core.standardsdocument'),
        ),
        migrations.CreateModel(
            name='TeacherStandardsSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_selections', to='core.standardsdocument')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='standardsdocument',
            index=models.Index(fields=['authority_program', 'subject', 'grade_level'], name='core_standa_authori_e49671_idx'),
        ),
        migrations.AddIndex(
            model_name='objectivenode',
            index=models.Index(fields=['document', 'parent', 'sort_order'], name='core_object_documen_2902bf_idx'),
        ),
        migrations.AddIndex(
            model_name='objectivenode',
            index=models.Index(fields=['document', 'code'], name='core_object_documen_13c65c_idx'),
        ),
        migrations.AddIndex(
            model_name='objectivenode',
            index=models.Index(fields=['document', 'internal_code'], name='core_object_documen_f6b9d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherstandardsselection',
            unique_together={('teacher', 'document')},
        ),
    ]
