# Generated by Django 5.2.9 on 2025-12-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_standards_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='aligned_objectives',
            field=models.ManyToManyField(blank=True, help_text='Learning objectives this course is aligned to', related_name='aligned_courses', to='core.objectivenode'),
        ),
        migrations.DeleteModel(
            name='TeacherStandardsSelection',
        ),
    ]
