# Generated by Django 5.2.9 on 2025-12-16 03:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_refactor_standards_to_course_alignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityProgramMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, max_length=500)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('isbn_10', models.CharField(blank=True, max_length=10)),
                ('isbn_13', models.CharField(blank=True, max_length=13)),
                ('source_url', models.URLField(help_text='Canonical link to resource', max_length=1000)),
                ('cover_image_url', models.URLField(blank=True, max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('book', 'Book'), ('guide', 'Guide'), ('practice_tests', 'Practice Tests'), ('video_series', 'Video Series'), ('course', 'Course')], max_length=20)),
                ('platform', models.CharField(choices=[('print', 'Print'), ('google_books', 'Google Books'), ('amazon', 'Amazon'), ('khan_academy', 'Khan Academy'), ('udemy', 'Udemy'), ('coursera', 'Coursera'), ('youtube', 'YouTube'), ('other', 'Other')], max_length=20)),
                ('is_official', models.BooleanField(default=False, help_text='True if published/endorsed by the authority')),
                ('is_unofficial', models.BooleanField(default=False, help_text='True for relevant but unofficial resources')),
                ('endorsement_notes', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=dict, help_text='e.g., {online_text: true, practice_tests: 5, video_hours: 12}')),
                ('retrieved_from', models.CharField(blank=True, choices=[('google_books', 'Google Books API'), ('amazon', 'Amazon'), ('manual', 'Manual Entry'), ('platform_scrape', 'Platform Scrape')], max_length=20)),
                ('retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_raw', models.JSONField(blank=True, default=dict, help_text='Raw API payload for audit')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authority_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.authorityprogram')),
            ],
            options={
                'verbose_name_plural': 'Authority program media',
                'ordering': ['-is_official', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AuthorityProgramMediaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g., official, exam_prep, beginner, video, open_course', max_length=50)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.authorityprogrammedia')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.AddIndex(
            model_name='authorityprogrammedia',
            index=models.Index(fields=['authority_program', 'is_official'], name='core_author_authori_e9b081_idx'),
        ),
        migrations.AddIndex(
            model_name='authorityprogrammedia',
            index=models.Index(fields=['isbn_13'], name='core_author_isbn_13_0d5240_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='authorityprogrammediatag',
            unique_together={('media', 'label')},
        ),
    ]
