# Generated by Django 5.2.9 on 2025-12-16 03:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_authority_program_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('sync_standards', 'Sync Standards'), ('hydrate_media', 'Hydrate Media'), ('import_standards_json', 'Import Standards from JSON'), ('bootstrap_courses', 'Bootstrap Platform Courses'), ('resync_authority', 'Re-sync Authority')], max_length=50)),
                ('idempotency_key', models.CharField(help_text='Unique key to prevent duplicate jobs (e.g., sync_standards:STATE_TX:Grades6-8)', max_length=255, unique=True)),
                ('params', models.JSONField(default=dict, help_text='Job-specific parameters')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress_pct', models.IntegerField(default=0, help_text='0-100 progress percentage')),
                ('progress_message', models.TextField(blank=True, help_text='Current operation description')),
                ('result', models.JSONField(blank=True, default=dict, help_text='Job result data')),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_backgr_status_e66a68_idx'), models.Index(fields=['job_type', 'status'], name='core_backgr_job_typ_0774c3_idx'), models.Index(fields=['idempotency_key'], name='core_backgr_idempot_ca8afa_idx')],
            },
        ),
    ]
