# Generated by Django 5.2.9 on 2025-12-16 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_background_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorityprogram',
            name='last_objectives_sync',
            field=models.DateTimeField(blank=True, help_text='Last successful objectives sync', null=True),
        ),
        migrations.AddField(
            model_name='authorityprogram',
            name='last_resources_sync',
            field=models.DateTimeField(blank=True, help_text='Last successful resources sync', null=True),
        ),
        migrations.AddField(
            model_name='authorityprogram',
            name='objectives_sync_status',
            field=models.CharField(choices=[('never', 'Never Synced'), ('syncing', 'Syncing'), ('success', 'Success'), ('error', 'Error')], default='never', max_length=20),
        ),
        migrations.AddField(
            model_name='authorityprogram',
            name='resources_sync_status',
            field=models.CharField(choices=[('never', 'Never Synced'), ('syncing', 'Syncing'), ('success', 'Success'), ('error', 'Error')], default='never', max_length=20),
        ),
        migrations.AddField(
            model_name='authorityprogrammedia',
            name='aligned_objectives',
            field=models.ManyToManyField(blank=True, help_text='Learning objectives this resource supports', related_name='supporting_resources', to='core.objectivenode'),
        ),
        migrations.AddField(
            model_name='standardsdocument',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('superseded', 'Superseded'), ('draft', 'Draft')], default='current', help_text='Document lifecycle status', max_length=20),
        ),
        migrations.AddField(
            model_name='standardsdocument',
            name='superseded_at',
            field=models.DateTimeField(blank=True, help_text='When this document was superseded', null=True),
        ),
        migrations.AddField(
            model_name='standardsdocument',
            name='superseded_by',
            field=models.ForeignKey(blank=True, help_text='Newer document that supersedes this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='core.standardsdocument'),
        ),
        migrations.AlterField(
            model_name='backgroundjob',
            name='job_type',
            field=models.CharField(choices=[('sync_standards', 'Sync Standards'), ('hydrate_media', 'Hydrate Media'), ('import_standards_json', 'Import Standards from JSON'), ('bootstrap_courses', 'Bootstrap Platform Courses'), ('resync_authority', 'Re-sync Authority'), ('sync_authority_objectives', 'Sync Authority Objectives'), ('sync_authority_resources', 'Sync Authority Resources')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='standardsdocument',
            index=models.Index(fields=['status'], name='core_standa_status_84f067_idx'),
        ),
    ]
