# Generated by Django 5.2.9 on 2025-12-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_sync_status_and_resource_alignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardsdocument',
            name='tier',
            field=models.CharField(choices=[('legislative', 'Legislative Authority'), ('standards_board', 'Standards Board'), ('testing_agency', 'Testing Agency'), ('publisher', 'Publisher Materials')], default='standards_board', help_text='Position in the standards pipeline hierarchy', max_length=20),
        ),
        migrations.AddIndex(
            model_name='standardsdocument',
            index=models.Index(fields=['tier'], name='core_standa_tier_4dfef3_idx'),
        ),
    ]
