# Generated by Django 5.2.9 on 2025-12-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_document_tier_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorityprogrammedia',
            options={'ordering': ['recommendation_tier', 'title'], 'verbose_name_plural': 'Authority program media'},
        ),
        migrations.RemoveIndex(
            model_name='authorityprogrammedia',
            name='core_author_authori_e9b081_idx',
        ),
        migrations.AddField(
            model_name='authorityprogrammedia',
            name='discovered_from_url',
            field=models.URLField(blank=True, help_text='URL where this resource was discovered', max_length=1000),
        ),
        migrations.AddField(
            model_name='authorityprogrammedia',
            name='recommendation_tier',
            field=models.CharField(choices=[('official', 'Official'), ('recommended', 'Recommended'), ('commonly_used', 'Commonly Used')], default='commonly_used', help_text='How authoritative is this resource?', max_length=20),
        ),
        migrations.AddField(
            model_name='authorityprogrammedia',
            name='recommending_organization',
            field=models.CharField(blank=True, help_text='Organization that recommended this resource', max_length=255),
        ),
        migrations.AlterField(
            model_name='authorityprogrammedia',
            name='is_official',
            field=models.BooleanField(default=False, help_text="DEPRECATED: Use recommendation_tier='official' instead"),
        ),
        migrations.AlterField(
            model_name='authorityprogrammedia',
            name='is_unofficial',
            field=models.BooleanField(default=False, help_text='DEPRECATED: Use recommendation_tier instead'),
        ),
        migrations.AlterField(
            model_name='authorityprogrammedia',
            name='media_type',
            field=models.CharField(choices=[('book', 'Book'), ('guide', 'Guide'), ('curriculum', 'Curriculum'), ('practice_tests', 'Practice Tests'), ('video_series', 'Video Series'), ('course', 'Course'), ('website', 'Website')], max_length=20),
        ),
        migrations.AlterField(
            model_name='authorityprogrammedia',
            name='platform',
            field=models.CharField(choices=[('print', 'Print'), ('authority', 'Authority Website'), ('google_books', 'Google Books'), ('amazon', 'Amazon'), ('khan_academy', 'Khan Academy'), ('udemy', 'Udemy'), ('coursera', 'Coursera'), ('youtube', 'YouTube'), ('district', 'School District'), ('publisher', 'Publisher'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='authorityprogrammedia',
            name='retrieved_from',
            field=models.CharField(blank=True, choices=[('authority_website', 'Authority Website'), ('professional_org', 'Professional Organization'), ('district_website', 'School District Website'), ('ai_discovery', 'AI-Assisted Discovery'), ('google_books_enrichment', 'Google Books (Metadata)'), ('manual', 'Manual Entry')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='authorityprogrammedia',
            index=models.Index(fields=['authority_program', 'recommendation_tier'], name='core_author_authori_49358e_idx'),
        ),
    ]
