# Generated by Django 5.2.9 on 2025-12-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_wida_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardsdocument',
            name='syllabus_code',
            field=models.CharField(blank=True, help_text="Course/syllabus identifier, e.g., '0580' for Cambridge IGCSE Mathematics", max_length=50),
        ),
        migrations.AlterField(
            model_name='standardsdocument',
            name='version_label',
            field=models.CharField(help_text="e.g., 'Adopted 2022', '2024-2026'", max_length=100),
        ),
    ]
