# Generated by Django 5.2.9 on 2025-12-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_add_syllabus_code_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorityprogrammedia",
            name="audience",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("student", "Student-Facing"),
                    ("teacher", "Teacher-Facing"),
                    ("both", "Student & Teacher"),
                ],
                default="general",
                help_text="Primary audience for this resource",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="authorityprogrammedia",
            name="is_companion",
            field=models.BooleanField(
                default=False,
                help_text="True if this is a companion/extra tied to a core text (e.g., DVD, online extras)",
            ),
        ),
        migrations.AddField(
            model_name="authorityprogrammedia",
            name="resource_category",
            field=models.CharField(
                choices=[
                    ("official", "Official"),
                    ("endorsed", "Endorsed"),
                    ("non_textbook", "Non-Textbook"),
                    ("offering", "Offering"),
                    ("youtube", "YouTube"),
                ],
                default="official",
                help_text="Grouping for resource display (official, endorsed, non-textbook, offering, youtube)",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="authorityprogrammedia",
            index=models.Index(
                fields=["authority_program", "resource_category"],
                name="core_author_authori_7d1f0f_idx",
            ),
        ),
    ]
