# Generated by Django 5.2.9 on 2025-12-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_resource_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorityprogrammedia",
            name="publisher_url",
            field=models.URLField(
                blank=True,
                help_text="Official publisher page / purchase link for this resource",
                max_length=1000,
            ),
        ),
    ]
