# Generated by Django 5.2.9 on 2025-12-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_add_publisher_url_to_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardsartifact",
            name="remote_url",
            field=models.URLField(blank=True, help_text="Original URL where artifact was fetched", max_length=1000),
        ),
    ]
