# Generated by Django 5.2.9 on 2025-12-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_add_remote_url_to_artifact"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardsdocument",
            name="description",
            field=models.TextField(blank=True, help_text="Official course description"),
        ),
    ]
