# Generated by Django 5.2.9 on 2025-12-17 06:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_description_to_standardsdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderTabConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_id', models.CharField(help_text="Tab identifier, e.g., 'overview', 'syllabus', 'objectives'", max_length=50)),
                ('label', models.CharField(help_text='Display label for the tab', max_length=100)),
                ('icon', models.CharField(default='bi-file-text', help_text="Bootstrap icon class, e.g., 'bi-file-text'", max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('fetch_method', models.CharField(choices=[('none', 'Static content only'), ('objectives', 'Fetch objectives tree'), ('resources', 'Fetch resources'), ('ai_extract', 'AI extraction from source_url'), ('custom', 'Custom provider method')], default='none', help_text='How to fetch data for this tab', max_length=50)),
                ('ai_extraction_prompt', models.TextField(blank=True, help_text='Custom prompt template for AI extraction. Use {course_name}, {syllabus_code}, {source_url} placeholders.')),
                ('custom_handler', models.CharField(blank=True, help_text="Dotted path to custom handler function for 'custom' fetch method", max_length=100)),
                ('static_description', models.TextField(blank=True, help_text='Static description shown in tab placeholder')),
                ('static_action_url_field', models.CharField(blank=True, help_text="Document field to use for action button URL (e.g., 'source_url')", max_length=50)),
                ('static_action_label', models.CharField(blank=True, help_text="Label for action button (e.g., 'View Official Syllabus')", max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'tab_id'],
            },
        ),
        migrations.CreateModel(
            name='TabDataCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_id', models.CharField(max_length=50)),
                ('data', models.JSONField(default=dict, help_text='Cached tab data as JSON')),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('fetch_status', models.CharField(choices=[('pending', 'Pending'), ('fetching', 'Fetching'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('fetch_method_used', models.CharField(blank=True, help_text='Which fetch method was used to populate this cache', max_length=50)),
                ('ai_model_used', models.CharField(blank=True, help_text='AI model used for extraction (if applicable)', max_length=100)),
                ('tokens_used', models.PositiveIntegerField(blank=True, help_text='Tokens consumed for AI extraction', null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='authorityprogrammedia',
            options={'ordering': ['resource_category', 'recommendation_tier', 'title'], 'verbose_name_plural': 'Authority program media'},
        ),
        migrations.RenameIndex(
            model_name='authorityprogrammedia',
            new_name='core_author_authori_5b0102_idx',
            old_name='core_author_authori_7d1f0f_idx',
        ),
        migrations.AddField(
            model_name='providertabconfig',
            name='authority',
            field=models.ForeignKey(blank=True, help_text='Authority-level config (applies to all programs unless overridden)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tab_configs', to='core.standardsauthority'),
        ),
        migrations.AddField(
            model_name='providertabconfig',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Program-specific config (overrides authority-level)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tab_configs', to='core.authorityprogram'),
        ),
        migrations.AddField(
            model_name='tabdatacache',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_data_cache', to='core.standardsdocument'),
        ),
        migrations.AddConstraint(
            model_name='providertabconfig',
            constraint=models.UniqueConstraint(fields=('authority', 'program', 'tab_id'), name='unique_tab_config_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='providertabconfig',
            constraint=models.CheckConstraint(condition=models.Q(('authority__isnull', False), ('program__isnull', False), _connector='OR'), name='tab_config_requires_authority_or_program'),
        ),
        migrations.AddIndex(
            model_name='tabdatacache',
            index=models.Index(fields=['document', 'fetch_status'], name='core_tabdat_documen_25ec7f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tabdatacache',
            unique_together={('document', 'tab_id')},
        ),
    ]
