# Generated by Django 5.2.9 on 2025-12-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_provider_tab_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='shuffle_answers',
            field=models.BooleanField(default=False, help_text='Randomize the order of answer choices within each question.'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='shuffle_questions',
            field=models.BooleanField(default=False, help_text='Present questions in random order for each student.'),
        ),
    ]
