# Generated by Django 5.2.9 on 2025-12-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_quiz_shuffle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembankchoice',
            name='freeze_position',
            field=models.BooleanField(default=False, help_text='Keep this choice in its position even when answer shuffling is enabled.'),
        ),
    ]
