# Generated by Django 5.2.9 on 2025-12-17 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_choice_freeze_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='freeze_position',
            field=models.BooleanField(default=False, help_text='Keep this question in its position even when question shuffling is enabled.'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='core.itembankquestion'),
        ),
    ]
