# Generated by Django 5.2.9 on 2025-12-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='invite_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='roster',
            name='invite_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
