# Generated by Django 5.2.9 on 2025-12-10 00:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_roster_invite_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_index', models.PositiveIntegerField()),
                ('view_start', models.DateTimeField()),
                ('view_end', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('scroll_depth_percent', models.FloatField(default=0)),
                ('revisit_count', models.PositiveIntegerField(default=0)),
                ('hesitation_count', models.PositiveIntegerField(default=0)),
                ('gloss_clicks', models.PositiveIntegerField(default=0)),
                ('copy_events', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_views', to='core.lesson')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='core.storysegment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['view_start'],
            },
        ),
    ]
